global using Azure.Identity;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Hosting;
global using TC.CloudGames.Contracts.Events.Games;
global using TC.CloudGames.Contracts.Events.Users;
global using TC.CloudGames.SharedKernel.Infrastructure.MessageBroker;
global using TC.CloudGames.SharedKernel.Infrastructure.Messaging;
global using Wolverine;
global using Wolverine.AzureServiceBus;
global using static TC.CloudGames.Messaging.Extensions.MessageNameHelper;
