<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="WolverineFx" Version="5.9.2" />
		<PackageReference Include="WolverineFx.AzureServiceBus" Version="5.9.2" />
		<PackageReference Include="WolverineFx.Marten" Version="5.9.2" />
		<PackageReference Include="WolverineFx.RabbitMQ" Version="5.9.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\TC.CloudGames.Contracts\TC.CloudGames.Contracts.csproj" />
	  <ProjectReference Include="..\TC.CloudGames.SharedKernel\TC.CloudGames.SharedKernel.csproj" />
	</ItemGroup>

</Project>
